from .student import Student
from .score import Score
from .attendance import Attendance
from .user import User
from .staff import Staff
from .teacher import Teacher  
from .schedule import Schedule
from .device import Device
from .schools import School