"""update all table

Revision ID: a982af81304b
Revises: 134e0c45e8ed
Create Date: 2025-09-15 00:16:13.903357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a982af81304b'
down_revision: Union[str, None] = '134e0c45e8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'class_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
