"""Add status to attendance

Revision ID: b3525462fe3e
Revises: cac5dbe05f89
Create Date: 2025-07-24 01:52:18.382033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3525462fe3e'
down_revision: Union[str, Sequence[str], None] = 'cac5dbe05f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'status')
    # ### end Alembic commands ###
