"""set lazy joined for teacher in schedule

Revision ID: bb9af1118bf3
Revises: 4f5cb19412ac
Create Date: 2025-06-23 21:04:58.170759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9af1118bf3'
down_revision: Union[str, Sequence[str], None] = '4f5cb19412ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
