"""add terminal event fields to attendance

Revision ID: cac5dbe05f89
Revises: 2342c0bd7c33
Create Date: 2025-07-18 08:34:22.859629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac5dbe05f89'
down_revision: Union[str, Sequence[str], None] = '2342c0bd7c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attendance', 'schools', ['school_id'], ['id'])
    op.drop_column('attendance', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('datetime', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'school_id')
    # ### end Alembic commands ###
